cmake_minimum_required(VERSION 4.2)
project(c_programming_practice C)

set(CMAKE_C_STANDARD 11)

add_executable(binary_search 01-basics/binary-search.c)

add_executable(conditions_and_loops 01-basics/conditions_and_loops.c)

add_executable(functions_arrays_strings 01-basics/functions_arrays_strings.c)

add_executable(hello_world 01-basics/hello_world.c)

add_executable(recursive_partition 01-basics/recursive-partition.c)

add_executable(user_input 01-basics/user_input.c)

add_executable(variables_and_sum 01-basics/variables_and_sum.c)

add_executable(calculator 02-projects/calculator.c)